name: workflow.yml
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test-code-style:
    name: Code style tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run isort
        run: isort --check --diff operetta
      - name: Run black
        run: black --check --diff operetta
      - name: Run mypy
        run: mypy operetta

  test-posix:
    name: Tests on Posix
    needs:
      - test-code-style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run isort
        run: isort --check --diff operetta
      - name: Run black
        run: black --check --diff operetta
      - name: Run mypy
        run: mypy operetta

  test-windows:
    name: Tests on Windows
    needs:
      - test-code-style
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run isort
        run: isort --check --diff operetta
      - name: Run black
        run: black --check --diff operetta
      - name: Run mypy
        run: mypy operetta
